version: '3.8'

services:
  frontend:
    image: esse1304/goldcastle:project1
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:4000
    networks:
      - my-network

  backend:
    image: esse1304/goldcastle:realbackendimage
    ports:
      - "4000:4000"
    networks:
      - my-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/cert:/etc/nginx/cert
    depends_on:
      - frontend
      - backend
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
